apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: tomcat-test-app 
spec:
  selector:
    matchLabels:
      app: tomcat-test
  replicas: 1 
  template:
    metadata:
      labels:
        app: tomcat-test 
    spec:
      containers:
      - name: tomcat-test
        image: ssilbory/alpine-tomcat:latest
        ports:
        - containerPort: 8080
---
apiVersion: "v1"
kind: Service
metadata:
  name: tomcat-test
spec:
  type: NodePort
  selector:
    app: tomcat-test
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080

